# Generated by Django 6.1 on 2026-08-23 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], max_length=10)),
                ('learning_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='native_language',
        ),
        migrations.AddField(
            model_name='languagepair',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='language_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.languagepair'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'language_pair', 'name'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='languagepair',
            constraint=models.UniqueConstraint(fields=('user', 'native_language', 'learning_language'), name='unique_language_pair_per_user'),
        ),
        migrations.AddConstraint(
            model_name='languagepair',
            constraint=models.CheckConstraint(condition=models.Q(('native_language', models.F('learning_language')), _negated=True), name='different_languages_in_pair'),
        ),
    ]
