# Generated by Django 6.1 on 2026-08-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_languagepair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='language_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.languagepair'),
        ),
    ]
