# Generated by Django 6.1 on 2026-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_language_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='learning_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
