# Generated by Django 6.1 on 2026-08-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_flashcard_ease_factor_flashcard_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='flascard',
            new_name='flashcard',
        ),
    ]
