# Generated by Django 6.1 on 2026-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_flascard_userprogress_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='ease_factor_before',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='interval_before',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='status_before',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='result',
            field=models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=10),
        ),
    ]
