# Generated by Django 6.1 on 2026-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprogress_ease_factor_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='ease_factor_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='interval_before',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status_before',
            field=models.CharField(max_length=12),
        ),
    ]
