# Generated by Django 6.1 on 2026-08-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprogress_ease_factor_before_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
