# Generated by Django 6.1 on 2026-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_game_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameattempt',
            new_name='api_gameatt_user_id_580437_idx',
            old_name='gameattempt_user_flashcard_type_idx',
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='gave_up',
            field=models.BooleanField(default=False),
        ),
    ]
