# Generated by Django 6.1 on 2026-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_gameattempt_user_flashcard_type_idx_api_gameatt_user_id_580437_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='correction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
