# Generated by Django 6.1 on 2026-09-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_gameattempt_correction_gameattempt_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepair',
            name='learning_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('da', 'Danish'), ('fi', 'Finnish'), ('el', 'Greek'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('cs', 'Czech'), ('hu', 'Hungarian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='languagepair',
            name='native_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('da', 'Danish'), ('fi', 'Finnish'), ('el', 'Greek'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('cs', 'Czech'), ('hu', 'Hungarian')], max_length=10),
        ),
    ]
